#!/bin/bash

obj=$1
diff=/tmp/$obj.diff
ctf=/tmp/$obj.ctf.c
dwarf=/tmp/$obj.dwarf.c
pahole -Z $obj
pahole -F ctf $obj > $ctf
pahole --flat_arrays -F dwarf $obj > $dwarf
diff -up $ctf $dwarf > $diff
if [ -s $diff ] ; then
	# vim /tmp/$obj.diff
	exit 0
else
	rm -f $diff $ctf $dwarf
fi
